### ISSUE TITLE
broken fluffy barrel dont open GUI

### ISSUE THREAD

**Issue by themrsnowmen** [NCBPFluffyBear/FluffyMachines#126] opened 2022-08-28 19:28 UTC
## Description (Required)
Small Fluffy Barrel not working.
Barrel GUI does not appear when right-clicking.
## Steps to reproduce the Issue (Required)
An error is output when starting the server and it is not working.

## Expected behavior (Required)
The Fluffly Barrel's GUI will open allowing you to put items in and out.

## Server Log / Error Report
https://pastebin.com/raw/SBBKSyir

## Environment (Required)

<img width="960" alt="無題" src="https://user-images.githubusercontent.com/112346248/187091180-5a1c7162-9805-4d75-afaa-a75119c4dddd.png">

  - Minecraft Version: 1.19.1
  - CS-CoreLib Version: n/a
  - Slimefun Version: RC 32
  - Fluffy Machines Version: DEV124

**Comment by NCBPFluffyBear** [comment] 2022-08-28 21:07
It looks like there was some kind of problem with loading some barrel data in. Did you tamper with the files before the server was started? Maybe it crashed?

This could also happen if another plugin is suppressing the event that is triggered when the barrels are placed.

To fix this just break the barrels that are affected and place them back down.
If the error still happens please let me know.

**Comment by themrsnowmen** [comment] 2022-08-29 04:58
No, it's not tampered with.
I just rebooted the server.
Do you need a plugin list other than slime fun4 and addons?

**Comment by NCBPFluffyBear** [comment] 2022-08-29 13:31
No, even if I had one I wouldn't be able to determine anything from their names.

If breaking them and placing them back down fixed the issue, I'll leave it as some kind of saving issue, since this has never been reported before. Please let me know if this takes care of it.

**Comment by themrsnowmen** [comment] 2022-08-29 13:56
However, if you place it once, it will disappear, and if you place it twice, it will work.
Also, all items will be lost.
thank you support

**Comment by NCBPFluffyBear** [comment] 2022-08-29 19:11
The latest build should "fix" your issue. I can't reproduce what you are describing, and given that nobody else has reported this, it seems to be a problem on only your server. However, I added a verification step that will fix broken mini barrels. Thanks for the report! Fixed in [84b753d](https://github.com/NCBPFluffyBear/FluffyMachines/commit/84b753dda467143ad5ad18b770fd1b8471a751aa)

**Closed by NCBPFluffyBear** 2022-08-29 19:11 UTC
Labels: bug
