### ISSUE TITLE
error console

### ISSUE THREAD

**Issue by ArrozElManko** [NCBPFluffyBear/FluffyMachines#73] opened 2021-02-23 12:15 UTC
## Description (Required)
every time I start my server does not load the addon and an error appears in the console

## Expected behavior (Required)
error

## Server Log / Error Report
https://hatebin.com/qnweuppucd

## Environment (Required)
https://imgur.com/5mjRisM

**Comment by NCBPFluffyBear** [comment] 2021-02-23 15:22
Duplicate of #72

**Closed by NCBPFluffyBear** 2021-02-23 15:22 UTC
Labels: bug
